name: Main

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    - cron: "* 6,9,12,15,20 * * *"

jobs:
  github-metrics-general:
    name: metrics-general
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ginan-jhs-science-club
          config_timezone: Asia/Tokyo
          filename: general.svg
          token: ${{ secrets.GH_TOKEN }}

          plugin_languages: yes
          plugin_languages_limit: 4
          plugin_languages_details: lines, bytes-size
          plugin_languages_sections: most-used
