name: Main

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    - cron: "* 6,9,12,15,20 * * *"

jobs:
  terraform:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: use token
        run: echo "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
  github-metrics-general:
    name: metrics-general
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ginan-jhs-science-club
          config_gemoji: yes
          config_timezone: Asia/Tokyo
          filename: general.svg
          token: ${{ steps.generate_token.outputs.token }}
          base: header
          config_order: base.header
