name: Main

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:

jobs:
  github-metrics-general:
    name: metrics-general
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ginan-jhs-science-club
          config_timezone: Asia/Tokyo
          filename: general.svg
          token: ${{ secrets.GH_TOKEN }}
          base: header
          config_order: base.header
