name: Main

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:

jobs:
  github-metrics-general:
    name: metrics-general
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Use token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
      - uses: lowlighter/metrics@latest
        with:
          user: ginan-jhs-science-club
          config_timezone: Asia/Tokyo
          filename: general.svg
          token: ${{ steps.generate_token.outputs.token }}
          base: header
          config_order: base.header
