name: Main

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    - cron: "* 6,9,12,15,20 * * *"

jobs:
  github-metrics-general:
    name: metrics-general
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ginan-jhs-science-club
          config_gemoji: yes
          config_timezone: Asia/Tokyo
          filename: general.svg
          token: ${{ steps.generate_token.outputs.token }}
          base: header
          config_order: base.header
