name: Main

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:

jobs:
  github-metrics-general:
    name: metrics-general
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate github token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: lowlighter/metrics@latest
        with:
          user: ginan-jhs-science-club
          config_gemoji: yes
          config_timezone: Asia/Tokyo
          filename: general.svg
          token: ${{ steps.generate-token.outputs.token }}
          base: header
          config_order: base.header
